/**
 * `process.env` 키 문자열 단일 출처 (오타 방지·검색·리팩터 용이).
 * 값 읽기는 `server-env-readers`, `gemini-review-reply`, `public-site` 등에서 처리.
 */
export const ENV_KEY = {
  NODE_ENV: "NODE_ENV",
  CRON_SECRET: "CRON_SECRET",
  WORKER_SECRET: "WORKER_SECRET",
  WORKER_MODE: "WORKER_MODE",
  DEBUG_BROWSER_HEADED: "DEBUG_BROWSER_HEADED",
  GEMINI_API_KEY: "GEMINI_API_KEY",
  GOOGLE_API_KEY: "GOOGLE_API_KEY",
  NEXT_PUBLIC_SUPABASE_URL: "NEXT_PUBLIC_SUPABASE_URL",
  NEXT_PUBLIC_SUPABASE_ANON_KEY: "NEXT_PUBLIC_SUPABASE_ANON_KEY",
  NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY: "NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY",
  SUPABASE_SERVICE_ROLE_KEY: "SUPABASE_SERVICE_ROLE_KEY",
  COOLSMS_API_KEY: "COOLSMS_API_KEY",
  COOLSMS_API_SECRET: "COOLSMS_API_SECRET",
  COOLSMS_SENDER: "COOLSMS_SENDER",
  SEND_SMS_HOOK_SECRET: "SEND_SMS_HOOK_SECRET",
  DEBUG_SEND_SMS_HOOK: "DEBUG_SEND_SMS_HOOK",
  NEXT_PUBLIC_APP_URL: "NEXT_PUBLIC_APP_URL",
  NEXT_PUBLIC_BASE_URL: "NEXT_PUBLIC_BASE_URL",
  NEXT_PUBLIC_VERCEL_URL: "NEXT_PUBLIC_VERCEL_URL",
  SELLER_REFERRAL_SECRET: "SELLER_REFERRAL_SECRET",
  PLATFORM_SESSION_ENCRYPTION_KEY: "PLATFORM_SESSION_ENCRYPTION_KEY",
  MEMBER_TRIAL_ELIGIBLE_SINCE_ISO: "MEMBER_TRIAL_ELIGIBLE_SINCE_ISO",
  MEMBER_FREE_PROMO_END_EXCLUSIVE_ISO: "MEMBER_FREE_PROMO_END_EXCLUSIVE_ISO",
  /** 선택. 미설정 시 `STORE_PLATFORM_ORDERS_RETENTION_DAYS` 상수(90) 사용 */
  STORE_PLATFORM_ORDERS_RETENTION_DAYS: "STORE_PLATFORM_ORDERS_RETENTION_DAYS",
} as const;
