/**
 * `process.env` 키 문자열 단일 출처 (오타 방지·검색·리팩터 용이).
 * 값 읽기는 `server-env-readers`, `gemini-review-reply`, `public-site` 등에서 처리.
 */
export const ENV_KEY = {
  NODE_ENV: "NODE_ENV",
  CRON_SECRET: "CRON_SECRET",
  WORKER_SECRET: "WORKER_SECRET",
  WORKER_MODE: "WORKER_MODE",
  DEBUG_BROWSER_HEADED: "DEBUG_BROWSER_HEADED",
  GEMINI_API_KEY: "GEMINI_API_KEY",
  GOOGLE_API_KEY: "GOOGLE_API_KEY",
  NEXT_PUBLIC_SUPABASE_URL: "NEXT_PUBLIC_SUPABASE_URL",
  NEXT_PUBLIC_SUPABASE_ANON_KEY: "NEXT_PUBLIC_SUPABASE_ANON_KEY",
  NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY: "NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY",
  SUPABASE_SERVICE_ROLE_KEY: "SUPABASE_SERVICE_ROLE_KEY",
  COOLSMS_API_KEY: "COOLSMS_API_KEY",
  COOLSMS_API_SECRET: "COOLSMS_API_SECRET",
  COOLSMS_SENDER: "COOLSMS_SENDER",
  /** 알림톡 발신번호 (`message.from`) */
  COOLSMS_SENDER_NUMBER: "COOLSMS_SENDER_NUMBER",
  /** 알림톡 발신 프로필 ID (`kakaoOptions.pfId`) */
  COOLSMS_PFID: "COOLSMS_PFID",
  SEND_SMS_HOOK_SECRET: "SEND_SMS_HOOK_SECRET",
  DEBUG_SEND_SMS_HOOK: "DEBUG_SEND_SMS_HOOK",
  NEXT_PUBLIC_APP_URL: "NEXT_PUBLIC_APP_URL",
  NEXT_PUBLIC_BASE_URL: "NEXT_PUBLIC_BASE_URL",
  NEXT_PUBLIC_VERCEL_URL: "NEXT_PUBLIC_VERCEL_URL",
  SELLER_REFERRAL_SECRET: "SELLER_REFERRAL_SECRET",
  PLATFORM_SESSION_ENCRYPTION_KEY: "PLATFORM_SESSION_ENCRYPTION_KEY",
  MEMBER_TRIAL_ELIGIBLE_SINCE_ISO: "MEMBER_TRIAL_ELIGIBLE_SINCE_ISO",
  MEMBER_FREE_PROMO_END_EXCLUSIVE_ISO: "MEMBER_FREE_PROMO_END_EXCLUSIVE_ISO",
  /** 선택. 미설정 시 `STORE_PLATFORM_ORDERS_RETENTION_DAYS` 상수(90) 사용 */
  STORE_PLATFORM_ORDERS_RETENTION_DAYS: "STORE_PLATFORM_ORDERS_RETENTION_DAYS",
  /** 선택. 불만족 리뷰 알림톡의 “댓글 등록하기 사용가이드” 버튼 링크 */
  OLIVIEW_REPLY_REGISTER_GUIDE_URL: "OLIVIEW_REPLY_REGISTER_GUIDE_URL",
  /** 선택. 결제 관련 알림톡의 “결제 등록하기 사용가이드” 버튼 링크 */
  OLIVIEW_BILLING_REGISTER_GUIDE_URL: "OLIVIEW_BILLING_REGISTER_GUIDE_URL",
  /** 선택. 결제 실패 알림톡의 “결제 등록하기 사용가이드” 버튼 링크(미설정 시 등록 가이드와 동일 취급 가능) */
  OLIVIEW_BILLING_MANAGE_GUIDE_URL: "OLIVIEW_BILLING_MANAGE_GUIDE_URL",
  /**
   * 불만족 리뷰 알림톡을 점주 외 "어드민 번호"로도 함께 발송(콤마 구분).
   * 예) "01091692939,01012345678"
   */
  OLIVIEW_DISSATISFIED_REVIEW_ADMIN_PHONES:
    "OLIVIEW_DISSATISFIED_REVIEW_ADMIN_PHONES",
  /**
   * 선택. 설정 시 KST 기준 해당 날짜(YYYY-MM-DD)까지 어드민 CC 발송 활성화.
   * 예) "2026-05-10"
   */
  OLIVIEW_DISSATISFIED_REVIEW_ADMIN_PHONES_ENABLED_UNTIL:
    "OLIVIEW_DISSATISFIED_REVIEW_ADMIN_PHONES_ENABLED_UNTIL",
} as const;
